### ISSUE TITLE
Error attempting to access file

### ISSUE THREAD

**Issue by hgardneriv** [cjustinjones/log-scanner#2]
Hello Chris,

I've modified lb.js to serve files in my local in my var log and get an error using curl to access a configured log file but am hitting an error. Any suggestions on how to get past this error?

**CURL Output**
`$ curl "http://localhost:3002/var/log/very-large.log"

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot read properties of undefined (reading &#39;createInterface&#39;)<br> &nbsp; &nbsp;at ReadLines (/Users/harrygardner/Documents/code/homework/chris_jones/log-scanner/util.js:10:38)<br> &nbsp; &nbsp;at async ReadLog (/Users/harrygardner/Documents/code/homework/chris_jones/log-scanner/readLog.js:12:21)<br> &nbsp; &nbsp;at async handleRequest (/Users/harrygardner/Documents/code/homework/chris_jones/log-scanner/worker.js:16:25)</pre>
</body>
</html>
`
**Server side output**
_Note: console.log added to display contents of workers map_

`$ npm run serve

> log-scanner@1.0.0 serve
> node lb.js 8080

WORKERS {
  workers: Map(4) {
    '/var/log/wifi.log' => { port: 3001, encoding: 'utf8' },
    '/var/log/very-large.log' => { port: 3002, encoding: 'utf8' },
    '/var/log/fsck_apfs.log' => { port: 3003, encoding: 'utf8' },
    '/var/log/fsck_apfs_error.log' => { port: 3004, encoding: 'utf8' }
  }
}
Starting worker for /var/log/wifi.log on port 3001
Starting worker for /var/log/very-large.log on port 3002
Starting worker for /var/log/fsck_apfs.log on port 3003
Starting worker for /var/log/fsck_apfs_error.log on port 3004
Load Balancer Server listening on PORT 8080
Worker listening on PORT 3002 for requests for /var/log/very-large.log
Worker listening on PORT 3001 for requests for /var/log/wifi.log
Worker listening on PORT 3003 for requests for /var/log/fsck_apfs.log
Worker listening on PORT 3004 for requests for /var/log/fsck_apfs_error.log
Reading /var/log/very-large.log for the first time
Error occured while handling request: Cannot read properties of undefined (reading 'createInterface')
TypeError: Cannot read properties of undefined (reading 'createInterface')
    at ReadLines (/Users/harrygardner/Documents/code/homework/chris_jones/log-scanner/util.js:10:38)
    at async ReadLog (/Users/harrygardner/Documents/code/homework/chris_jones/log-scanner/readLog.js:12:21)
    at async handleRequest (/Users/harrygardner/Documents/code/homework/chris_jones/log-scanner/worker.js:16:25)
`
**Environment**

$ uname -a
Darwin XXX-MacBook-Pro-2.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

$ nvm list
       v12.18.4
       v14.15.0
       v14.15.1
->     v16.13.2
         system

**Comment by cjustinjones** [comment]
Hello Harry,

Can you share the file in question?  If not, can you tell me the size?

CJ

**Comment by cjustinjones** [comment]
I created a 1GB file to use to test, and I've switched to v16.13.2, and I can duplicate the problem.  Running the code in v17.3.0 does not yield this same issue, the worker gets past reading the file, but it throws an exception during the json serialization in the response due to the payload being too large for JSON.stringify() (used internally by express).
So probably two fixes here:
1) If it is necessary to run the code using v16.3.2, then it seams the internal readline module can't be used and that function would have to be implemented
2) If the entire contents of very large files needs to be downloaded, then the payload needs to be streamed to the HTTP response; I believe Express supports this via the write() function on the response object.  If the contents need to be JSON (as they currently are), then I need to handle the JSON serialization as a stream too because JSON.stringify() will throw an exception.

**Comment by cjustinjones** [comment]
I've tried out a third party module for streaming json responses as fix for the second issue, and it works; however, it's highlighted a limitation to the rather naive approach I took to loading the file using readline.  The thinking was to read the contents of the file into memory (spreading this load over multiple workers) so that subsequent requests would be fast.  However, with this large log file (1GB), searching the lines for keywords began to slow the response down.  I think the approach needs to be modified to read the file each time and do the keyword scan at that time, returning the results.

**Comment by cjustinjones** [comment]
I suppose to be most efficient, it should read the file from back to front (to satisfy the first requirement), scanning for lines that match the keywords and then returning whenever the limit is met or until it reaches the beginning of the file.

**Comment by hgardneriv** [comment]
Hey Chris, sorry for the delay. I was testing with a 6 GB file. Yes reading in reverse order is a much better way to approach the problem.

**Comment by cjustinjones** [comment]
So I've written a readable stream interface that handles reading and reversing the file in chunks. Need to alter the filter and limit code to act as a transform stream so that I can pipe the reversed stream into it.  Should have that done tomorrow.
